/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kalana Hettiarachchi
 */
public class reservation extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    
    
    public reservation(String u) {
        initComponents();
        
        con=DbConnect.connect();
        
        tableLoad();
    }
    
    
    public void tableLoad(){
    
       try{
           
            String sql="SELECT Customer_ID,First_Name,Last_Name,Address,Customer_Mobile,Email,Nationality,National_ID,AC_or_Not,Room_Type,Num_of_People,Room_Number,hours FROM customer";
        pst=con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        table.setModel(DbUtils.resultSetToTableModel(rs));
        
       }
       
       catch(Exception e){
           System.out.println(e);
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        wwwwee = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmobile = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        wwwwee1 = new javax.swing.JLabel();
        nation = new javax.swing.JComboBox<>();
        ac = new javax.swing.JComboBox<>();
        wwwwee2 = new javax.swing.JLabel();
        wwwwee3 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        wwwwee4 = new javax.swing.JLabel();
        people = new javax.swing.JComboBox<>();
        wwwwee5 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        wwwwee6 = new javax.swing.JLabel();
        rnum = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        wwwwee7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        hours = new javax.swing.JTextField();
        cid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cusid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        roomnum = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        nnic = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setText("Customer ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel4.setText("Address");

        wwwwee.setText("Email");

        jLabel6.setText("Customer Mobile");

        wwwwee1.setText("Nationality");

        nation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Srilankan", "Other" }));

        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A/c", "NonA/C" }));

        wwwwee2.setText("A/C or Non A/C");

        wwwwee3.setText("National ID");

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });

        wwwwee4.setText("Num of People");

        people.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        people.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleActionPerformed(evt);
            }
        });

        wwwwee5.setText("Room Type");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Family" }));

        wwwwee6.setText("Room Number");

        rnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnumActionPerformed(evt);
            }
        });

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Cost:");

        cost.setBackground(new java.awt.Color(204, 204, 204));
        cost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        wwwwee7.setText("Hours Spent:");

        jButton3.setText("CALCULATE & PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(wwwwee4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wwwwee3)
                                    .addComponent(wwwwee2)
                                    .addComponent(wwwwee5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2))
                                                .addComponent(wwwwee)
                                                .addComponent(wwwwee1))
                                            .addGap(53, 53, 53)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(mail)
                                                .addComponent(cmobile)
                                                .addComponent(fname)
                                                .addComponent(lname)
                                                .addComponent(address)
                                                .addComponent(nation, 0, 158, Short.MAX_VALUE)
                                                .addComponent(cid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(wwwwee6)
                                                .addComponent(wwwwee7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                            .addComponent(rnum, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(delete)
                                        .addGap(18, 18, 18)
                                        .addComponent(update)
                                        .addGap(18, 18, 18)
                                        .addComponent(add))
                                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wwwwee1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee3)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wwwwee2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee5)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee4)
                    .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee6)
                    .addComponent(rnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wwwwee7)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(add))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel5.setText("Search for Customers");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Search for Room Details");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        backbtn.setText("<< Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kalana Hettiarachchi\\Desktop\\cal.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );

        jButton4.setText("Check Availability");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Search by national ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(166, 166, 166)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(nnic, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(32, 32, 32)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton4)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       
         
         String ffname=fname.getText();
         String llname=lname.getText();
         String aaddress=address.getText();
         String ccmobile=cmobile.getText();
         String mmail=mail.getText();
         String nnation=nation.getSelectedItem().toString();
         String nnic=nic.getText();
         String aac=ac.getSelectedItem().toString();
         String ttype=type.getSelectedItem().toString();
         String ppeople=people.getSelectedItem().toString();
         String rrnum=rnum.getText();
         String Hours=hours.getText();
         
         
         
        try{
            
             String q="INSERT INTO customer (First_Name,Last_Name,Address,Customer_Mobile,Email,Nationality,National_ID,AC_or_Not,Room_Type,Num_of_People,Room_Number,hours) VALUES ('"+ffname+"','"+llname+"','"+aaddress+"','"+ccmobile+"','"+mmail+"','"+nnation+"','"+nnic+"','"+aac+"','"+ttype+"','"+ppeople+"','"+rrnum+"','"+Hours+"')";
         pst=con.prepareStatement(q);
         pst.execute();
         tableLoad();
        
        }
        catch(Exception e){
            System.out.println(e);
        }
         
    }//GEN-LAST:event_addActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void peopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peopleActionPerformed

    private void rnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnumActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       int r=table.getSelectedRow();
       
       String ccid=table.getValueAt(r, 0).toString();
       String ffname=table.getValueAt(r, 1).toString();
       String llname=table.getValueAt(r, 2).toString();
       String aaddress=table.getValueAt(r, 3).toString();
       String ccmobile=table.getValueAt(r, 4).toString();
       String mmail=table.getValueAt(r, 5).toString();
       String nnation=table.getValueAt(r, 6).toString();
       String nnid=table.getValueAt(r, 7).toString();
       String aac=table.getValueAt(r, 8).toString();
       String ttype=table.getValueAt(r, 9).toString();
       String ppeople=table.getValueAt(r, 10).toString();
       String rrnum=table.getValueAt(r, 11).toString();
       String Hours=table.getValueAt(r, 12).toString();
       
       
       cid.setText(ccid);
       fname.setText(ffname);
       lname.setText(llname);
       address.setText(aaddress);
       cmobile.setText(ccmobile);
       mail.setText(mmail);
       nation.setSelectedItem(nnation);
       nic.setText(nnid);
       ac.setSelectedItem(aac);
       type.setSelectedItem(ttype);
       people.setSelectedItem(ppeople);
       rnum.setText(rrnum);
       hours.setText(Hours);
       
       
     
    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        
      int x = JOptionPane.showConfirmDialog(null,"Do you realy want to update");
      
      if(x==0){
         String ccid=cid.getText();
         String ffname=fname.getText();
         String llname=lname.getText();
         String aaddress=address.getText();
         String ccmobile=cmobile.getText();
         String mmail=mail.getText();
         String nnation=nation.getSelectedItem().toString();
         String nnic=nic.getText();
         String aac=ac.getSelectedItem().toString();
         String ttype=type.getSelectedItem().toString();
         String ppeople=people.getSelectedItem().toString();
         String rrnum=rnum.getText();
         String Hours=hours.getText();
         
         
         String sql="UPDATE customer SET First_Name='"+ffname+"',Last_Name='"+llname+"',Address='"+aaddress+"',Customer_Mobile='"+ccmobile+"',Email='"+mmail+"',Nationality='"+nnation+"',National_ID='"+nnic+"',AC_or_Not='"+aac+"',Room_Type='"+ttype+"',Num_of_People='"+ppeople+"',Room_Number='"+rrnum+"' ,hours='"+Hours+"' WHERE Customer_ID='"+ccid+"'";
         
         
         try{
               pst=con.prepareStatement(sql);
         pst.execute();
         tableLoad();
         }
         catch(Exception e){
             System.out.println(e);
         }
       
      }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
            int x=JOptionPane.showConfirmDialog(null,"Do you realy want delete this record");
            
            if(x==0){
                
                String ccid=cid.getText();
                
               try{
                    String sql="DELETE from customer WHERE Customer_ID='"+ccid+"'";
                pst=con.prepareStatement(sql);
                pst.execute();
                tableLoad();
               }
               catch(Exception e){
                   System.out.println(e);
               }
            }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         String ccusid=cusid.getText();
         
         String sql="SELECT Customer_ID,First_Name,Last_Name,Address,Customer_Mobile,Email,Nationality,National_ID,AC_or_Not,Room_Type,Num_of_People,Room_Number,hours FROM customer WHERE Customer_ID LIKE '%"+ccusid+"%'";
         
         try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
             
         }
         catch(Exception e){
             System.out.println(e);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
          String rroomnum=roomnum.getText();
         
         String sql="SELECT  Customer_ID,Customer_ID,First_Name,Last_Name,Address,Customer_Mobile,Email,Nationality,National_ID,AC_or_Not,Room_Type,Num_of_People,hours FROM customer WHERE Room_Number LIKE '%"+rroomnum+"%'";
         
         try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
             
         }
         catch(Exception e){
             System.out.println(e);
    }                                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        main m = new main("");
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         float total=0;  
         float total1=10;
         
         try{
         
         String ccid=cid.getText();
         String aac=ac.getSelectedItem().toString();
         String ttype=type.getSelectedItem().toString();
         String Hours=hours.getText();
         String ffname=fname.getText();
         String llname=lname.getText();
         
         
         
         if(aac=="A/c"){
                  total=total+2000;
                   if(ttype=="Single"){
                      total=total+500;
                  }
                   if(ttype=="Double"){
                      total=total+1000;
                  }
                   if(ttype=="Family"){
                      total=total+1500;
                  }
                  
          }
         
         else if(aac=="NonA/C"){
             
              total=total+1000;
                   if(ttype=="Single"){
                      total=total+500;
                  }
                   if(ttype=="Double"){
                      total=total+1000;
                  }
                   if(ttype=="Family"){
                      total=total+1500;
                  }
         }
         
         float hourpay=Float.parseFloat(Hours);
           System.out.println(total);
           total=total+(100*hourpay);
           System.out.println("dddd "+total);
           
         
         
          String sql="SELECT  * FROM food where Customer_ID='"+ccid+"'";
         
           
   
                pst=con.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()){

            String Break=rs.getString(2);
            String Lunch=rs.getString(3);
            String Dinner=rs.getString(4);
            String Tea=rs.getString(5);
            String Peo=rs.getString(6);
            
                    System.out.println(Break);
               float pe = Float.parseFloat(Peo);
                   
                   
               if(Break.equals("1")){
                     total1=total1+200; 
               }
               if(Break.equals("2")){
                     total1=total1+300; 
               }
               if(Break.equals("3")){
                     total1=total1+400; 
               }
               if(Break.equals("4")){
                     total1=total1+500; 
               }
               if(Lunch.equals("1")){
                     total1=total1+200; 
               }
               if(Lunch.equals("2")){
                     total1=total1+300; 
               }
               if(Lunch.equals("3")){
                     total1=total1+400; 
               }
               if(Lunch.equals("4")){
                     total1=total1+500; 
               }
               if(Dinner.equals("1")){
                     total1=total1+200; 
               }
               if(Dinner.equals("2")){
                     total1=total1+300; 
               }
               if(Dinner.equals("3")){
                     total1=total1+400; 
               }
               if(Dinner.equals("4")){
                     total1=total1+500; 
               }
               if(Tea.equals("1")){
                     total1=total1+200; 
               }
               if(Tea.equals("2")){
                     total1=total1+300; 
               }
               if(Tea.equals("3")){
                     total1=total1+400; 
               }
               if(Tea.equals("4")){
                     total1=total1+500; 
               }
             
              
                
                
                total1=total1*pe;
                
                }
            
         
                               
         
             System.out.println(total1);
         
             total=total+total1;
            
             String pay=Float.toString(total);
             cost.setText(pay+"LKR");
             
            
            
             
              File file=new File("e:/invoice.txt");
            FileWriter fw=new FileWriter(file);
            fw.write("Customer ID "+ccid+"\r\n"+"\r\n");
            fw.write("*******************************"+"\r\n");
            fw.write("Fisrt Name "+ffname+"\r\n"+"\r\n");
             fw.write("*******************************"+"\r\n");
            
            fw.write("Last Name "+llname+"\r\n"+"\r\n");
             fw.write("*******************************"+"\r\n");
            
            fw.write("the total cost "+pay+"\r\n"+"\r\n");
            fw.flush();
            fw.close();
    }
                catch(Exception e){
             System.out.println(e);
    }         
            
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        availability a = new availability();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
           String nnnic=nnic.getText();
         
         String sql="SELECT Customer_ID,First_Name,Last_Name,Address,Customer_Mobile,Email,Nationality,National_ID,AC_or_Not,Room_Type,Num_of_People,Room_Number,hours FROM customer WHERE National_ID LIKE '%"+nnnic+"%'";
         
         try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
             
         }
         catch(Exception e){
             System.out.println(e);
    }                                 
    }//GEN-LAST:event_jButton5ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ac;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel cid;
    private javax.swing.JTextField cmobile;
    private javax.swing.JLabel cost;
    private javax.swing.JTextField cusid;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JComboBox<String> nation;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField nnic;
    private javax.swing.JComboBox<String> people;
    private javax.swing.JTextField rnum;
    private javax.swing.JTextField roomnum;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update;
    private javax.swing.JLabel wwwwee;
    private javax.swing.JLabel wwwwee1;
    private javax.swing.JLabel wwwwee2;
    private javax.swing.JLabel wwwwee3;
    private javax.swing.JLabel wwwwee4;
    private javax.swing.JLabel wwwwee5;
    private javax.swing.JLabel wwwwee6;
    private javax.swing.JLabel wwwwee7;
    // End of variables declaration//GEN-END:variables
}
